# config.py - Com lista completa de POPs

API_URL = "https://hexagon.computei.srv.br/ocorrencias"
TEMPO_ATUALIZACAO = 30
ZOOM_PADRAO = 13
CENTRO_MAPA = [-22.9068, -43.1729]

# ✅ CORES PARA PRIORIDADES
COR_PRIORIDADE = {
    "MUITO ALTA": "#8B0000",     # Vermelho escuro
    "ALTA": "#FF6B6B",            # Vermelho
    "MÉDIA": "#FFD700",           # Amarelo
    "BAIXO": "#90EE90"            # Verde claro
}

# ✅ TIPOS DE MAPA 
TIPOS_MAPA = [
    "OpenStreetMap",
    "CartoDB Positron",
    "CartoDB Voyager",
    "MapBox Standard Day",
    "MapBox Standard Night",
    "MapBox Satellite"
]

# ✅ LISTA COMPLETA DE POPs (FIXA - não depende dos dados)
LISTA_POPS = [
    "POP01: ACIDENTE SEM VITIMA",
    "POP02: ACIDENTE COM VITIMA",
    "POP03: ACIDENTE COM OBITO",
    "POP04: INCENDIO EM VEICULO",
    "POP05: BOLSAO DE AGUA EM VIA",
    "POP06: MANIFESTACAO EM LOCAL PUBLICO",
    "POP07: INCENDIO EM IMOVEL",
    "POP08: SINAIS DE TRANSITO COM MAU FUNCIONAMENTO",
    "POP09: REINTEGRACAO DE POSSE",
    "POP10: QUEDA DE ARVORE",
    "POP11: QUEDA DE POSTE",
    "POP12: ACIDENTE COM QUEDA DE CARGA",
    "POP13: INCENDIO NO ENTORNO DE VIAS PUBLICAS",
    "POP14: INCENDIO DENTRO DE TUNEIS",
    "POP15: VAZAMENTO DE AGUA E ESGOTO",
    "POP16: FALTA CRITICA DE ENERGIA OU APAGAO",
    "POP17: IMPLOSAO",
    "POP18: ESCAPAMENTO DE GAS",
    "POP19: EVENTO NAO PROGRAMADO",
    "POP20: ATROPELAMENTO",
    "POP21: AFUNDAMENTO DE PISTA OU BURACO NA VIA",
    "POP22: ABALROAMENTO",
    "POP23: OBRA/MANUTENÇÃO EM LOCAL PUBLICO",
    "POP24: OPERACAO POLICIAL",
    "POP25: ACIONAMENTO DE SIRENES",
    "POP26: ALAGAMENTO",
    "POP27: ENCHENTE OU INUNDACAO",
    "POP28: LAMINA DE AGUA",
    "POP29: ACIDENTE AMBIENTAL",
    "POP30: INCIDENTE COM BUEIRO",
    "POP31: QUEDA DE ARVORE SOBRE FIACAO",
    "POP32: RESIDUOS NA VIA",
    "POP33: INCENDIO EM VEGETACAO",
    "POP34: DESLIZAMENTO",
    "POP35: QUEDA DE ESTRUTURA DE ALVENARIA",
    "POP36: RESGATE OU REMOCAO DE ANIMAIS TERRESTRES E AEREOS",
    "POP37: REMOCAO DE ANIMAIS MORTOS NA AREIA",
    "POP38: RESGATE DE ANIMAL MARINHO PRESO EM REDE OU ENCALHADO",
    "POP39: ANIMAL EM LOCAL PUBLICO",
    "POP40: QUEDA DE CARGA VIVA DE GRANDE PORTE",
    "POP41: QUEDA DE CARGA VIVA DE PEQUENO PORTE",
    "POP42: PROTOCOLO DE VIA",
    "POP43: PROTOCOLO DE CICLOVIA",
    "POP44: ENGUICO NA VIA",
    "POP49: PROTOCOLO DE PARQUES",
    "POP50: OCORRENCIA EM PARQUE AEROPORTUARIO",
    "POP51: INTERRUPÇÃO PARCIAL OU TOTAL DE MODAL DE TRANSPORTE",
    "POP52: FIAÇÃO PARTIDA/ARREADA",
    "POP53: RESSACA/MARÉ ALTA",
]

# ✅ POPS QUE APARECEM SELECIONADOS POR DEFAULT
# CUSTOMIZE AQUI: adicione os códigos dos POPs que quer por padrão
# Exemplo: ["POP01", "POP05", "POP26"]
POPS_DEFAULT = [
    "POP05",  # BOLSAO DE AGUA EM VIA
    "POP26",  # ALAGAMENTO
    "POP27",  # ENCHENTE OU INUNDACAO
    "POP28",  # LAMINA DE AGUA
]


MAPBOX_TOKEN = "pk.eyJ1IjoiYXVndXN0b21lbGxvIiwiYSI6ImNqZXI4Z2JzNzIyd2MycW5xaW1tNW43d2oifQ.7EAN3MxRSv1z4qrjUWDJ-w"  # ← Coloque sua chave aqui se tiver